CREATE TABLE IF NOT EXISTS `aggregated_trips` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `date` datetime NOT NULL COMMENT 'Day and time that is being reported',
  `supplier_id` varchar(30) NOT NULL DEFAULT '' COMMENT 'Name of the supplier',
  `total_rides` int(11) NOT NULL COMMENT 'Total vehicles that initiated at least one ride within the reported hour',
  `total_vehicle_rides` int(11) NOT NULL,
  `total_available_vehicles` int(11) NOT NULL,
  `total_dist_traveled` float NOT NULL,
  `passing_time` float NOT NULL COMMENT 'Total time (in minutes with passengers) of the rides that started during the reported time',
  `request_time` float NOT NULL COMMENT 'Total time (in minutes with travel request and without passenger), measured from the time when a driver accepts a ride request, until he/she picks up the passenger or the trip is canceled',
  `empty_time` float NOT NULL COMMENT 'Total time (in minutes without a travel request and without a passenger), measured from the time when a driver indicated that he/she was available, until the moment he/she received a request or disconnected from the application',
  `eod_multiplier` float NOT NULL COMMENT 'Multiplier of average fare for rides that start in each of the EOD Districts during the reported hour',
  `accessibility` float NOT NULL COMMENT 'Percentage of rides that initiated in vehicles with trunks with a capacity of at least L1 = minimum length of 95 cm; L2 = minimum length of 90 cm; H = minimum height of 50 cm; P = minimum depth of 90 cm',
  `female_operator` float NOT NULL COMMENT 'Percentage of rides that started during the reported time and that had a female driver',
  `eod_start` int(11) NOT NULL COMMENT 'Total rides that started in each EOD District during the reported hour',
  `eod_end` int(11) NOT NULL COMMENT 'Total rides completed in each EOD District during the reported hour',
  `eod_pass_dist` float NOT NULL COMMENT 'Total distance traveled (in kilometers with passengers), in each EOD District on rides that began during the reported hour',
  `eod_pass_time` int(11) NOT NULL COMMENT 'Total time (in minutes with passengers), in each EOD District on trips that began during the reported hour',
  `request_dist` float NOT NULL COMMENT 'Total distance traveled (in kilometers, with travel request and without passenger) measured from the moment in which the driver accepts a ride request, until the moment he/she picks up the passenger or the trip is canceled',
  `empty_dist` float NOT NULL COMMENT 'Total distance traveled (in kilometers, without travel request and without passenger) measured from the moment in which the driver indicated that he/she was available, until the moment he/she received a request or disconnected from the application',
  `eod_request_dist` float NOT NULL COMMENT 'Total distance traveled (in kilometers in each EOD District) with ride request and without passenger, measured from the moment in which the driver accepts a travel request, until the moment he/she picks up the passenger or the trip is canceled',
  `eod_request_time` float NOT NULL COMMENT 'Total time (in minutes in each EOD District) with ride request and without passenger, measured from the time when the driver accepts a ride request, until he/she picks up the passenger or the trip is canceled',
  `eod_empty_dist` float NOT NULL COMMENT 'Total distance traveled (in kilometers in each EOD District) without a ride request and without a passenger, measured from the moment the driver indicated he/she was available, until the moment he/she received a request or disconnected from the application',
  `eod_empty_time` float NOT NULL COMMENT 'Total time (in minutes in each EOD District) without ride request and without passenger, measured from the time when the operator indicated that it was available, until the moment he/she received an application or disconnected from the application',
  PRIMARY KEY (`id`),
  KEY `date` (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;