{
 "title": "Mixpanel - Bollobas",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Incoming topics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bollobas_injestion_ingestion_messages_total[5m])) by (topic, provider)",
     "legendFormat": "{{topic}}-{{provider}}"
    },
    {
     "expr": "sum(rate(bollobas_injestion_ingestion_messages_total[5m])) by (provider)",
     "legendFormat": "total-{{provider}}"
    }
   ]
  },
  {
   "title": "Messages  handled by mixpanel handlers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bollobas_mixpanel_messages_total[5m])) by (topic, provider)",
     "legendFormat": "{{topic}}-{{provider}}"
    },
    {
     "expr": "sum(rate(bollobas_mixpanel_messages_total[5m])) by (provider)",
     "legendFormat": "total-{{provider}}"
    }
   ]
  },
  {
   "title": "Configuration update errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sum(rate(bollobas_configuration_messages_total{success!=\"true\"}[5m])) by (entity) / sum(rate(bollobas_configuration_messages_total{success=\"true\"}[5m])) by (entity)",
     "legendFormat": "total-{{entity}}"
    }
   ]
  },
  {
   "title": "Ingestion Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sum(rate(bollobas_injestion_ingestion_messages_total{processed=\"true\", success!=\"true\"}[5m])) by (provider) /sum(rate(bollobas_injestion_ingestion_messages_total{processed=\"true\"}[5m])) by (provider)",
     "legendFormat": "total-{{provider}}"
    },
    {
     "expr": "100 * sum(rate(bollobas_injestion_ingestion_messages_total{processed=\"true\", success!=\"true\"}[5m])) by (provider, topic) /sum(rate(bollobas_injestion_ingestion_messages_total{processed=\"true\"}[5m])) by (provider, topic)",
     "legendFormat": "{{topic}}-{{provider}}"
    }
   ]
  },
  {
   "title": "Mixpanel processing errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sum(rate(bollobas_mixpanel_messages_total{processed=\"true\", success!=\"true\"}[5m])) by (provider, topic) / sum(rate(bollobas_mixpanel_messages_total{processed=\"true\"}[5m])) by (provider, topic)",
     "legendFormat": "{{topic}}-{{provider}}"
    },
    {
     "expr": "100 * sum(rate(bollobas_mixpanel_messages_total{processed=\"true\", success!=\"true\"}[5m])) by (provider) / sum(rate(bollobas_mixpanel_messages_total{processed=\"true\"}[5m])) by (provider)",
     "legendFormat": "total-{{provider}}"
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_memory_usage_bytes{container_name=\"bollobas\", namespace=\"mixpanel\"})",
     "legendFormat": "Total pods"
    }
   ]
  },
  {
   "title": "Memory usage per pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (container_memory_usage_bytes{container_name=\"bollobas\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Goroutines Number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{app_kubernetes_io_name=\"bollobas\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Mixpanel 95th percentile latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum  by (le, provider) (rate(bollobas_mixpanel_latency_seconds_bucket[5m])))",
     "legendFormat": "total-{{provider}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum  by (le, provider, topic) (rate(bollobas_mixpanel_latency_seconds_bucket[5m])))",
     "legendFormat": "{{topic}}-{{provider}}"
    }
   ]
  },
  {
   "title": "Ingestion 95th percentile latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum  by (le, provider) (rate(bollobas_injestion_latency_seconds_bucket[5m])))",
     "legendFormat": "total-{{provider}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum  by (le, provider, topic) (rate(bollobas_injestion_latency_seconds_bucket[5m])))",
     "legendFormat": "{{topic}}-{{provider}}"
    }
   ]
  },
  {
   "title": "Mixpanel missed messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (sum(rate(bollobas_injestion_republished_messages_total{}[5m])) - sum(rate(bollobas_mixpanel_messages_total{processed!=\"true\", provider=\"mangos\"}[5m])) )/sum(rate(bollobas_mixpanel_messages_total{processed=\"true\", provider=\"mangos\"}[5m]))",
     "legendFormat": "percentage"
    }
   ]
  },
  {
   "title": "Configuration 95th percentile latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum  by (le, provider, url) (rate(bollobas_configuration_latency_seconds_bucket[5m])))",
     "legendFormat": "{{url}}-{{provider}}"
    }
   ]
  }
 ]
}