// Code generated by counterfeiter. DO NOT EDIT.
package internalfakes

import (
	"context"
	"sync"

	"github.com/taxibeat/bollobas/internal"
)

type FakeAggregatedTripsRepository struct {
	AddStub        func(context.Context, *internal.AggregatedTrips) error
	addMutex       sync.RWMutex
	addArgsForCall []struct {
		arg1 context.Context
		arg2 *internal.AggregatedTrips
	}
	addReturns struct {
		result1 error
	}
	addReturnsOnCall map[int]struct {
		result1 error
	}
	GetAllStub        func(context.Context, internal.DateFilter) ([]internal.AggregatedTrips, error)
	getAllMutex       sync.RWMutex
	getAllArgsForCall []struct {
		arg1 context.Context
		arg2 internal.DateFilter
	}
	getAllReturns struct {
		result1 []internal.AggregatedTrips
		result2 error
	}
	getAllReturnsOnCall map[int]struct {
		result1 []internal.AggregatedTrips
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAggregatedTripsRepository) Add(arg1 context.Context, arg2 *internal.AggregatedTrips) error {
	fake.addMutex.Lock()
	ret, specificReturn := fake.addReturnsOnCall[len(fake.addArgsForCall)]
	fake.addArgsForCall = append(fake.addArgsForCall, struct {
		arg1 context.Context
		arg2 *internal.AggregatedTrips
	}{arg1, arg2})
	fake.recordInvocation("Add", []interface{}{arg1, arg2})
	fake.addMutex.Unlock()
	if fake.AddStub != nil {
		return fake.AddStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.addReturns
	return fakeReturns.result1
}

func (fake *FakeAggregatedTripsRepository) AddCallCount() int {
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	return len(fake.addArgsForCall)
}

func (fake *FakeAggregatedTripsRepository) AddCalls(stub func(context.Context, *internal.AggregatedTrips) error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = stub
}

func (fake *FakeAggregatedTripsRepository) AddArgsForCall(i int) (context.Context, *internal.AggregatedTrips) {
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	argsForCall := fake.addArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAggregatedTripsRepository) AddReturns(result1 error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = nil
	fake.addReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAggregatedTripsRepository) AddReturnsOnCall(i int, result1 error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = nil
	if fake.addReturnsOnCall == nil {
		fake.addReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAggregatedTripsRepository) GetAll(arg1 context.Context, arg2 internal.DateFilter) ([]internal.AggregatedTrips, error) {
	fake.getAllMutex.Lock()
	ret, specificReturn := fake.getAllReturnsOnCall[len(fake.getAllArgsForCall)]
	fake.getAllArgsForCall = append(fake.getAllArgsForCall, struct {
		arg1 context.Context
		arg2 internal.DateFilter
	}{arg1, arg2})
	fake.recordInvocation("GetAll", []interface{}{arg1, arg2})
	fake.getAllMutex.Unlock()
	if fake.GetAllStub != nil {
		return fake.GetAllStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getAllReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAggregatedTripsRepository) GetAllCallCount() int {
	fake.getAllMutex.RLock()
	defer fake.getAllMutex.RUnlock()
	return len(fake.getAllArgsForCall)
}

func (fake *FakeAggregatedTripsRepository) GetAllCalls(stub func(context.Context, internal.DateFilter) ([]internal.AggregatedTrips, error)) {
	fake.getAllMutex.Lock()
	defer fake.getAllMutex.Unlock()
	fake.GetAllStub = stub
}

func (fake *FakeAggregatedTripsRepository) GetAllArgsForCall(i int) (context.Context, internal.DateFilter) {
	fake.getAllMutex.RLock()
	defer fake.getAllMutex.RUnlock()
	argsForCall := fake.getAllArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAggregatedTripsRepository) GetAllReturns(result1 []internal.AggregatedTrips, result2 error) {
	fake.getAllMutex.Lock()
	defer fake.getAllMutex.Unlock()
	fake.GetAllStub = nil
	fake.getAllReturns = struct {
		result1 []internal.AggregatedTrips
		result2 error
	}{result1, result2}
}

func (fake *FakeAggregatedTripsRepository) GetAllReturnsOnCall(i int, result1 []internal.AggregatedTrips, result2 error) {
	fake.getAllMutex.Lock()
	defer fake.getAllMutex.Unlock()
	fake.GetAllStub = nil
	if fake.getAllReturnsOnCall == nil {
		fake.getAllReturnsOnCall = make(map[int]struct {
			result1 []internal.AggregatedTrips
			result2 error
		})
	}
	fake.getAllReturnsOnCall[i] = struct {
		result1 []internal.AggregatedTrips
		result2 error
	}{result1, result2}
}

func (fake *FakeAggregatedTripsRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	fake.getAllMutex.RLock()
	defer fake.getAllMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAggregatedTripsRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ internal.AggregatedTripsRepository = new(FakeAggregatedTripsRepository)
