replicaCount: 1

image:
  registry: registry.private.k8s.management.thebeat.co/beat/
  name: bollobas
  tag: v1.0.0
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  targetPort: 8100
  port: 80

env:
  PATRON_LOG_LEVEL: info
  PATRON_HTTP_DEFAULT_PORT: 8100
  BOLLOBAS_KAFKA_DRIVER_TOPIC: driver_analytics
  BOLLOBAS_KAFKA_PASSENGER_TOPIC: passenger_analytics
  BOLLOBAS_KAFKA_TIMEOUT: 10s
  BOLLOBAS_KAFKA_CONNECTION_STRING: kafka::9092
  BOLLOBAS_KAFKA_GROUP: "arcns1"
  BOLLOBAS_CIPHER_KEY: ""
  BOLLOBAS_INIT_VECTOR: ""
  BOLLOBAS_LOCATION: "sandbox"
  BOLLOBAS_MIXPANEL_TOKEN: ""

ingress:
  enabled: false
  # type can be either public or private
  type: private
  annotations: {}
    # kubernetes.io/tls-acme: "true"
  path: /
  host: bollobas
  clusterSuffix: private.k8s.sandbox.thebeat.co

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   cpu: 200m
   memory: 256Mi
  requests:
   cpu: 100m
   memory: 128Mi

monitoring:
  enabled: true
  path: /metrics
  port: 8100

# This will enable blackbox exporter probes in the designated path.
# If the probe get non 2xx responses for greates than "for:" period it will sent an alert to alertmanager
# Alertmanager will route the notification according to severity to a slack channel or pagerduty
blackboxProbe:
  enabled: true
  path: /health
  for: 5m
  severity: warning
  port: 8100

livenessProbe:
  httpGet:
    path: /health
    port: 8100

readinessProbe:
  httpGet:
    path: /health
    port: 8100

autoscaling:
  enabled: false
  # minReplicas: 3
  # maxReplicas: 10
  # metrics:
  # - type: Resource
  #   resource:
  #     name: cpu
  #     targetAverageUtilization: 80
  # - type: Resource
  #   resource:
  #     name: memory
  #     targetAverageUtilization: 80

nodeSelector: {}

tolerations: []

affinity: {}
