definitions:
  view.AggregatedTrips:
    properties:
      accesibilidad:
        type: number
      dist_pasajero:
        type: number
      dist_pasajero_eod:
        type: number
      dist_solicitud:
        type: number
      dist_solicitud_eod:
        type: number
      dist_vacio:
        type: number
      dist_vacio_eod:
        type: number
      fecha:
        type: string
      fin_eod:
        type: integer
      id:
        type: integer
      id_proveedor:
        type: string
      inicio_eod:
        type: integer
      multiplicador_eod:
        type: number
      operador_mujer:
        type: number
      tiempo_pasajero:
        type: number
      tiempo_pasajero_eod:
        type: integer
      tiempo_solicitud:
        type: number
      tiempo_solicitud_eod:
        type: number
      tiempo_vacio:
        type: number
      tiempo_vacio_eod:
        type: number
      tot_veh_disp:
        type: integer
      tot_veh_viaje:
        type: integer
      tot_viajes:
        type: integer
    type: object
  view.ErrorSwagger:
    properties:
      error:
        type: string
    type: object
  view.OperatorStats:
    properties:
      cant_viajes:
        type: integer
      edad:
        type: string
      genero:
        type: integer
      horas_conectado:
        type: string
      horas_viaje:
        type: string
      id:
        type: integer
      id_operador:
        type: string
      ingreso_totales:
        type: string
      tiempo_registro:
        type: integer
    type: object
  view.TrafficIncident:
    properties:
      distancia_viaje:
        type: string
      hecho_trans:
        type: integer
      id:
        type: integer
      licencia:
        type: string
      placa:
        type: string
      tiempo_hecho:
        type: string
      tiempo_viaje:
        type: string
      ubicacion:
        type: string
    type: object
info:
  contact:
    name: RDXP3
    url: https://confluence.taxibeat.com/display/TEAM404/RDXP3+-+TechnoMules
  description: Bollobas microservice is responsible for any analytics that go through
    Beat's backend platform.
  license:
    name: BEAT Mobility Services
  title: Bollobas
  version: 1.0.0
paths:
  /hecho_transito:
    get:
      consumes:
      - application/json
      parameters:
      - description: start date (epoch time)
        in: query
        name: from
        type: integer
      - description: end date (epoch time)
        in: query
        name: to
        type: integer
      - description: Limit Value
        in: query
        name: limit
        type: integer
      - description: Offset Value
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/view.TrafficIncident'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorSwagger'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorSwagger'
      summary: Get return all the traffic incidents
      tags:
      - bollobas
  /stats_operador:
    get:
      consumes:
      - application/json
      parameters:
      - description: Limit Value
        in: query
        name: limit
        type: integer
      - description: Offset Value
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/view.OperatorStats'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorSwagger'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorSwagger'
      summary: Get return all the operator stats
      tags:
      - bollobas
  /viajes_agregados:
    get:
      consumes:
      - application/json
      parameters:
      - description: start date (epoch time)
        in: query
        name: from
        type: integer
      - description: end date (epoch time)
        in: query
        name: to
        type: integer
      - description: Limit Value
        in: query
        name: limit
        type: integer
      - description: Offset Value
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/view.AggregatedTrips'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorSwagger'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorSwagger'
      summary: Get All the aggregated rides
      tags:
      - bollobas
schemes:
- http
swagger: "2.0"
tags:
- name: bollobas
